name: Build and test Java app

on:
  push:
    branches:
      - add-ci-cd

jobs:

  test-app:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export env variables
        run: |
          . ./sets/set-env.sh

      - name: Start docker-compose
        run: |
          docker compose -f compose.prod.yml up -d

      - name: Test API endpoint
        run: |
          curl -f http://localhost:8080/api/employees

      - name: Show logs on failure
        if: failure()
        run: docker compose -f compose.prod.yml logs

      - name: Shutdown
        if: always()
        run: docker compose -f compose.prod.yml down -v --rmi all
