name: Build and test Java app

on:
  push:
    branches:
      - add-ci-cd

jobs:

  test-app:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export env variables
        run: |
          pwd
          . ./sets/set-env.sh

      - name: Start docker-compose
        run: |
          docker compose -f compose.prod.yml up -d

      - name: Wait for API healthcheck
        run: |
          echo "Waiting for API to become healthy..."
          for i in {1..30}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose -f compose.prod.yml ps -q api))
            if [ "$STATUS" = "healthy" ]; then
              echo "API is healthy"
              exit 0
            fi
            sleep 5
          done
          echo "API did not become healthy"
          exit 1

      - name: Test API endpoint
        run: |
          curl -f http://localhost:8080/api/employees

      - name: Show logs on failure
        if: failure()
        run: docker compose -f compose.prod.yml logs

      - name: Shutdown
        if: always()
        run: docker compose -f compose.prod.yml down -v --rmi all
